### ISSUE TITLE
ST 2.3.6 ipa

### ISSUE THREAD

**Issue by RetiredOldCat** [alecm/SmartThingsAlecM#1]
Hello Alec.  I am looking for a .ipa copy for ST 2.3.6 (or earlier).  Have had no success with obvious sources.  Can you help.
tnx, mg (mgoodman22@cox.net)

**Comment by alecm** [comment]
Hello @RetiredOldCat ,,

I'm afraid I'm just a common user with a forked Smartthings repository - don't keep any of the old ipas on hand.  You might want to reach out to support.

Thanks!
Alec
